// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hello_cpp
std::string hello_cpp();
RcppExport SEXP _agentgraph_hello_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hello_cpp());
    return rcpp_result_gen;
END_RCPP
}
// http_get_cpp
Rcpp::List http_get_cpp(std::string url);
RcppExport SEXP _agentgraph_http_get_cpp(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(http_get_cpp(url));
    return rcpp_result_gen;
END_RCPP
}
// chat_native_cpp
Rcpp::List chat_native_cpp(std::string api_key, std::string model, std::string base_url, Rcpp::List messages_r, std::string system_prompt);
RcppExport SEXP _agentgraph_chat_native_cpp(SEXP api_keySEXP, SEXP modelSEXP, SEXP base_urlSEXP, SEXP messages_rSEXP, SEXP system_promptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type api_key(api_keySEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_url(base_urlSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type messages_r(messages_rSEXP);
    Rcpp::traits::input_parameter< std::string >::type system_prompt(system_promptSEXP);
    rcpp_result_gen = Rcpp::wrap(chat_native_cpp(api_key, model, base_url, messages_r, system_prompt));
    return rcpp_result_gen;
END_RCPP
}
// chat_parallel_cpp
Rcpp::List chat_parallel_cpp(std::string api_key, std::string model, std::string base_url, Rcpp::List messages_list, std::string system_prompt, int n_threads);
RcppExport SEXP _agentgraph_chat_parallel_cpp(SEXP api_keySEXP, SEXP modelSEXP, SEXP base_urlSEXP, SEXP messages_listSEXP, SEXP system_promptSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type api_key(api_keySEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_url(base_urlSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type messages_list(messages_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type system_prompt(system_promptSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(chat_parallel_cpp(api_key, model, base_url, messages_list, system_prompt, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// parse_llm_response_cpp
Rcpp::List parse_llm_response_cpp(std::string response_json);
RcppExport SEXP _agentgraph_parse_llm_response_cpp(SEXP response_jsonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type response_json(response_jsonSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_llm_response_cpp(response_json));
    return rcpp_result_gen;
END_RCPP
}
// run_graph_cpp
Rcpp::List run_graph_cpp(Rcpp::List graph_config, Rcpp::List state_data, Rcpp::List messages_r, Rcpp::List tools_r, int n_threads, Rcpp::Nullable<Rcpp::Function> on_token, std::string resume_from, int tool_server_port);
RcppExport SEXP _agentgraph_run_graph_cpp(SEXP graph_configSEXP, SEXP state_dataSEXP, SEXP messages_rSEXP, SEXP tools_rSEXP, SEXP n_threadsSEXP, SEXP on_tokenSEXP, SEXP resume_fromSEXP, SEXP tool_server_portSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type graph_config(graph_configSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type state_data(state_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type messages_r(messages_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tools_r(tools_rSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type on_token(on_tokenSEXP);
    Rcpp::traits::input_parameter< std::string >::type resume_from(resume_fromSEXP);
    Rcpp::traits::input_parameter< int >::type tool_server_port(tool_server_portSEXP);
    rcpp_result_gen = Rcpp::wrap(run_graph_cpp(graph_config, state_data, messages_r, tools_r, n_threads, on_token, resume_from, tool_server_port));
    return rcpp_result_gen;
END_RCPP
}
// test_tool_cpp
Rcpp::List test_tool_cpp(std::string tool_name, std::string args_json);
RcppExport SEXP _agentgraph_test_tool_cpp(SEXP tool_nameSEXP, SEXP args_jsonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type tool_name(tool_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type args_json(args_jsonSEXP);
    rcpp_result_gen = Rcpp::wrap(test_tool_cpp(tool_name, args_json));
    return rcpp_result_gen;
END_RCPP
}
// rpc_call_cpp
Rcpp::List rpc_call_cpp(int port, std::string tool_name, std::string args_json);
RcppExport SEXP _agentgraph_rpc_call_cpp(SEXP portSEXP, SEXP tool_nameSEXP, SEXP args_jsonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type port(portSEXP);
    Rcpp::traits::input_parameter< std::string >::type tool_name(tool_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type args_json(args_jsonSEXP);
    rcpp_result_gen = Rcpp::wrap(rpc_call_cpp(port, tool_name, args_json));
    return rcpp_result_gen;
END_RCPP
}
// rpc_stress_cpp
Rcpp::List rpc_stress_cpp(int port, std::string tool_name, std::string args_json, int n_calls, int n_threads);
RcppExport SEXP _agentgraph_rpc_stress_cpp(SEXP portSEXP, SEXP tool_nameSEXP, SEXP args_jsonSEXP, SEXP n_callsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type port(portSEXP);
    Rcpp::traits::input_parameter< std::string >::type tool_name(tool_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type args_json(args_jsonSEXP);
    Rcpp::traits::input_parameter< int >::type n_calls(n_callsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rpc_stress_cpp(port, tool_name, args_json, n_calls, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_agentgraph_hello_cpp", (DL_FUNC) &_agentgraph_hello_cpp, 0},
    {"_agentgraph_http_get_cpp", (DL_FUNC) &_agentgraph_http_get_cpp, 1},
    {"_agentgraph_chat_native_cpp", (DL_FUNC) &_agentgraph_chat_native_cpp, 5},
    {"_agentgraph_chat_parallel_cpp", (DL_FUNC) &_agentgraph_chat_parallel_cpp, 6},
    {"_agentgraph_parse_llm_response_cpp", (DL_FUNC) &_agentgraph_parse_llm_response_cpp, 1},
    {"_agentgraph_run_graph_cpp", (DL_FUNC) &_agentgraph_run_graph_cpp, 8},
    {"_agentgraph_test_tool_cpp", (DL_FUNC) &_agentgraph_test_tool_cpp, 2},
    {"_agentgraph_rpc_call_cpp", (DL_FUNC) &_agentgraph_rpc_call_cpp, 3},
    {"_agentgraph_rpc_stress_cpp", (DL_FUNC) &_agentgraph_rpc_stress_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_agentgraph(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
