# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_cpp <- function() {
    .Call(`_agentgraph_hello_cpp`)
}

http_get_cpp <- function(url) {
    .Call(`_agentgraph_http_get_cpp`, url)
}

chat_native_cpp <- function(api_key, model, base_url, messages_r, system_prompt) {
    .Call(`_agentgraph_chat_native_cpp`, api_key, model, base_url, messages_r, system_prompt)
}

chat_parallel_cpp <- function(api_key, model, base_url, messages_list, system_prompt, n_threads) {
    .Call(`_agentgraph_chat_parallel_cpp`, api_key, model, base_url, messages_list, system_prompt, n_threads)
}

parse_llm_response_cpp <- function(response_json) {
    .Call(`_agentgraph_parse_llm_response_cpp`, response_json)
}

run_graph_cpp <- function(graph_config, state_data, messages_r, tools_r, n_threads = 0L, on_token = NULL, resume_from = "", tool_server_port = 0L) {
    .Call(`_agentgraph_run_graph_cpp`, graph_config, state_data, messages_r, tools_r, n_threads, on_token, resume_from, tool_server_port)
}

test_tool_cpp <- function(tool_name, args_json) {
    .Call(`_agentgraph_test_tool_cpp`, tool_name, args_json)
}

rpc_call_cpp <- function(port, tool_name, args_json) {
    .Call(`_agentgraph_rpc_call_cpp`, port, tool_name, args_json)
}

rpc_stress_cpp <- function(port, tool_name, args_json, n_calls = 8L, n_threads = 4L) {
    .Call(`_agentgraph_rpc_stress_cpp`, port, tool_name, args_json, n_calls, n_threads)
}

